version: '3.5'
services: 
    smart-news-mongo:
        image: mongo:latest
        restart: always
        command: mongod --port 11111
        container_name: smart-news-mongo
    smart-news-server:
        build: .
        image: smart-news-server
        depends_on: 
            - smart-news-mongo
        ports: 
            - "9082:9082"
        expose:
            - 9082